package com.guang.mapper;

import com.guang.po.PartnerInfo;
import com.guang.po.PartnerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int countByExample(PartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int deleteByExample(PartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int insert(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int insertSelective(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    List<PartnerInfo> selectByExample(PartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    PartnerInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") PartnerInfo record, @Param("example") PartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int updateByExample(@Param("record") PartnerInfo record, @Param("example") PartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int updateByPrimaryKeySelective(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_partner_info
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    int updateByPrimaryKey(PartnerInfo record);
}