package com.guang.po;

import java.util.Date;

public class BizType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.type_name
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.creator_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.create_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.modifier_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private Long modifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.modify_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.remark
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_biz_type.desc
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.id
     *
     * @return the value of openapi_biz_type.id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.id
     *
     * @param id the value for openapi_biz_type.id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.type_name
     *
     * @return the value of openapi_biz_type.type_name
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.type_name
     *
     * @param typeName the value for openapi_biz_type.type_name
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.creator_id
     *
     * @return the value of openapi_biz_type.creator_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.creator_id
     *
     * @param creatorId the value for openapi_biz_type.creator_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.create_time
     *
     * @return the value of openapi_biz_type.create_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.create_time
     *
     * @param createTime the value for openapi_biz_type.create_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.modifier_id
     *
     * @return the value of openapi_biz_type.modifier_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.modifier_id
     *
     * @param modifierId the value for openapi_biz_type.modifier_id
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.modify_time
     *
     * @return the value of openapi_biz_type.modify_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.modify_time
     *
     * @param modifyTime the value for openapi_biz_type.modify_time
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.remark
     *
     * @return the value of openapi_biz_type.remark
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.remark
     *
     * @param remark the value for openapi_biz_type.remark
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_biz_type.desc
     *
     * @return the value of openapi_biz_type.desc
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_biz_type.desc
     *
     * @param desc the value for openapi_biz_type.desc
     *
     * @mbggenerated Wed Aug 17 13:51:31 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}