package com.guang.po;

import java.util.Date;

public class PartnerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.partner_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.merchant_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.partner_name
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String partnerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.open_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.security
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String security;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.access_key
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.effective_date
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private Long effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.is_active
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.remark
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.desc
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.create_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openapi_partner_info.modify_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.id
     *
     * @return the value of openapi_partner_info.id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.id
     *
     * @param id the value for openapi_partner_info.id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.partner_id
     *
     * @return the value of openapi_partner_info.partner_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.partner_id
     *
     * @param partnerId the value for openapi_partner_info.partner_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.merchant_id
     *
     * @return the value of openapi_partner_info.merchant_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.merchant_id
     *
     * @param merchantId the value for openapi_partner_info.merchant_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.partner_name
     *
     * @return the value of openapi_partner_info.partner_name
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.partner_name
     *
     * @param partnerName the value for openapi_partner_info.partner_name
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName == null ? null : partnerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.open_id
     *
     * @return the value of openapi_partner_info.open_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.open_id
     *
     * @param openId the value for openapi_partner_info.open_id
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.security
     *
     * @return the value of openapi_partner_info.security
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getSecurity() {
        return security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.security
     *
     * @param security the value for openapi_partner_info.security
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setSecurity(String security) {
        this.security = security == null ? null : security.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.access_key
     *
     * @return the value of openapi_partner_info.access_key
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.access_key
     *
     * @param accessKey the value for openapi_partner_info.access_key
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey == null ? null : accessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.effective_date
     *
     * @return the value of openapi_partner_info.effective_date
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public Long getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.effective_date
     *
     * @param effectiveDate the value for openapi_partner_info.effective_date
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setEffectiveDate(Long effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.is_active
     *
     * @return the value of openapi_partner_info.is_active
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.is_active
     *
     * @param isActive the value for openapi_partner_info.is_active
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.remark
     *
     * @return the value of openapi_partner_info.remark
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.remark
     *
     * @param remark the value for openapi_partner_info.remark
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.desc
     *
     * @return the value of openapi_partner_info.desc
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.desc
     *
     * @param desc the value for openapi_partner_info.desc
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.create_time
     *
     * @return the value of openapi_partner_info.create_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.create_time
     *
     * @param createTime the value for openapi_partner_info.create_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openapi_partner_info.modify_time
     *
     * @return the value of openapi_partner_info.modify_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openapi_partner_info.modify_time
     *
     * @param modifyTime the value for openapi_partner_info.modify_time
     *
     * @mbggenerated Wed Nov 16 11:13:01 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}